name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  style-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install "poetry>=1.8,<2"

      - name: Install dependencies (incl. dev)
        run: |
          poetry install --no-interaction --no-root --with dev

      - name: Black – check formatting
        run: |
          poetry run black --check .

      - name: Ruff – lint
        run: |
          poetry run ruff check .

      - name: Mypy – static type analysis
        run: |
          poetry run mypy .
